### ISSUE TITLE
Not fully working with "postcss-loader": "^2.0.0"

### ISSUE THREAD

**Issue by karol-f** [ElemeFE/postcss-salad#16]
Not fully working with "postcss-loader": "^2.0.0".

There are some breaking changes - https://github.com/postcss/postcss-loader/releases/tag/v2.0.0

**Comment by baiyaaaaa** [comment]
I will soon update it .

**Comment by baiyaaaaa** [comment]
release 2.0.0

**Comment by karol-f** [comment]
Thank you!
