### ISSUE TITLE
这个项目是什么样的境况？会长期维护下去吗？

### ISSUE THREAD

**Issue by dingyiming** [ElemeFE/postcss-salad#3]
看起来还是不错的，轻便，好用些，但还没发release，所以想问问这个项目有和打算？

**Comment by baiyaaaaa** [comment]
关注度太低，目前也没有发现bug或者其他问题，所以一直考虑后续的开发和维护。内部一直在使用中。

**Comment by yelingfeng** [comment]
我觉得挺好的 可以更出些开发上的优势 跟其他预处理的比较 实例 会不会更好些
